spring.application.name=clinica

spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_ddd
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.show-sql=true
spring.jpa.format-sql=true
